	/*

        Copyright (c) 2014 Cooperative Institute for Mesoscale Meteorological Studies (CIMMS) and the University of Oklahoma

        Author:         Dr. Chris Karstens
        Email:          chris.karstens@noaa.gov
        Description:    Contains the following:
                                1. initializes all variables

        */

	// initialize varabiables
	if(site == 'MPAR'){
		var volumes = 4;
	}
	else{
		var volumes = 5;
	}
	var caseStartTimes = {
		'20100522':Date.UTC(2010,4,22,23,9,00),
		'20150426':Date.UTC(2015,03,26,23,00,00),
		'20150506':Date.UTC(2015,04,06,21,59,00),
		'20150624':Date.UTC(2015,05,24,18,00,00),
		'20160331':Date.UTC(2016,02,31,23,15,00),
		'20160509':Date.UTC(2016,04,9,20,30,00),
		'20160524':Date.UTC(2016,04,24,22,30,00),
		'20160525':Date.UTC(2016,04,25,22,45,00),
		'20160901':Date.UTC(2016,8,1,17,55,00)
	};
	var caseStartNames = {
               	'20150506':'Training Case (ALL)',
               	'20160509':'Case #2 (TOR/SVR)',
               	'20160524':'Case #3 (TOR/SVR)',
               	'20160525':'Case #1 (TOR/SVR)',
               	'20160901':'Case #4 (LGT)'
       	};
	var popup;
	var featureList;
	var grids = [];
        var gridData = [];
	var deriveVector = false;
	var selFeature;
	var hail_threshold = 1;
	var posh_threshold = 0;
	var duration = 45;
	var dir = 270;
	var dir_orig = dir;
	var spd = 32;
	var max_prob = 100;
	var default_spacing = 2;
	var spacing = 0.02;
	var dilation = 3;
	var ftime = 0;
	var default_dir = 10;
	var default_spd = 5;
	var default_duration = 60;
	var durationValLast = 60;
	var default_dilation = 3;
	var lat;
	var lon;
	var id = -1;
	var x2;
	var y2;
	var xNorm;
	var yNorm;
	var evtType = 'prob';
	var p1;
	var p2;
	var map;
	var x_point;
	var y_point;
	var manual_dir = false;
	var newFeature = false;
	var direction_slider = null;
	var duration_slider = null;
	var time_slider = null;
	var threatColor = 'rgb(255,0,0)';
	var default_threatColor = 'rgb(255,0,0)';
	var centroid_last;
	var threat_orig;
	var rot_last = 0;
	var start_point;
	var ftime_last = 0;
	var proj = new OpenLayers.Projection('EPSG:4326');
	var proj2 = new OpenLayers.Projection('EPSG:900913');
	var geographicProj = new OpenLayers.Projection('EPSG:4326');
	var mercatorProj = new OpenLayers.Projection('EPSG:900913');
	//var default_probs = [20,25,30,35,40,50,60,65,65,65,65,60,60,55,50,45,45,45,40,40,35,35,35,30,25];
	//var default_probs = [80,75,65,60,60,55,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50];
	//var default_probs = [80,75,65,60,60,55,50,45,40,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35];
	var default_probs = [100,92,83,75,67,58,50,42,33,25,17,8,0,0,0,0,0,0,0,0,0,0,0,0,0];
	var default_sig_probs = [30,30,35,40,45,45,40,35,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30];
	var default_speeds = [32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32];
	var default_dirs = [270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270];
	var default_dirs_orig = [270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270,270];
	var tiles = new Array(5);
	var scans = new Array();
	var radarImages = new Array();
	var radarImageLast = '';
	var allScans = new Array();
	var tempId;
	var tempDilation;
	var tempDuration;
	var tempProbs;
	var tempProbsLast;
	var tempSpeeds;
	var tempDirs;
	var tempDirs_orig;
	var tempThreatColor;
	var tempSpd;     
	var tempDir;
	var tempValidStart;
	var tempValidEnd;
	var currentTilt = 'td_tilt_0';
	var lastTilt = 'td_tilt_0';
	var currentScan;
	var lastScan;
	var now;
	var nowLast;
	var currentTime;
	var currentTimeLast = -999;
	var valid_start_last = -999;
	var initTime;
	var initArchiveTime;
	var initArchiveTimeOrig;
	var currentScanTime;
	var idLast;
	var clone;
	var cloneCenter;
	var cloneCenterLast;
	var cloneNew2;
	var cloneNew3;
	var newAttrs;
	var attrs;
	var resetPoly = false;
	var showRadar = true;
	var updateThreat = false;
	var chartSet = false;
	var timeValue;
	var buttonLast;
	var lastScale = 1;
	var wofR = false;
	var probIdx = 0;
	var tiltMax;
	var objHistory = [];
	var undoing = false;
	var redoHistory = [];
	var threatRotate = true;
	var featureTypes = [];
	var modifyFeature = null;
	var startPoint = null;
	var startClone;
	var moveThreatTime;
	var gridIndex = 0;
	var colorScale = '5Levels';
	var gridsLength = -999;
	var timeMin = 0;
	var torTracks;
	var product = 'Reflectivity';
	var field = product;
	var lat;
	var lon;
	var archive;
	var config = false;
	var direction_slider;
	var time_slider;
	var grid_slider;
	var tSlide = false;
	var ftime = 0;
	var duration_last;
	var oldButton = 'prob1';
	var timeValTilt;
	var newFeature2 = false;
	var timeValTrip;
	var wofRecommender = false;
	var drawType = null;
	var drawTypeOrig = null;
	var updateThreatOrig;
	var objectAttrs;
	var backgroundCheck = false;
	var floaterBounds;
	var bounds;
	var floaterBoundsNELat;
	var floaterBoundsNELon;
	var floaterBoundsSWLat;
	var floaterBoundsSWLon;
	var boundsNELat;
       	var boundsNELon;
       	var boundsSWLat;
       	var boundsSWLon;
	var floaterSites = [];
	var floaterImages;
	var tiltIndex;
	var maxTilt;
	var lyrTimePrevScan;
	var cwa;
	var wfos;
	var updates = 0;
	var cloneTime;
	var centroidTime = 0;
	var centers = {};
	var counties_layer;
	var cwa_layer;
	var contourNumber;
	var selOpt;
	var selOpt2;
	var hazOpt;
	var pending = false;
	var modelLayer;
	var imgNameLast = null;
	var timerInt;
	var logTime = 0;
	var modelOpacity = 1;
	var radarOpacity = 1;
	var Navigation = null;
	var initOpts;
	var obsLayer;
	var imgNameLast2;
	var monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
	var myrorssCase = false;
	var wofCase = false;
	var phiFloaterInfo;
	var past = false;
	var kmeans = false;
	var assigningStart = false;
	var initReadThreats = true;
	var validEnding = 0;
	var banList = [];
	var drawProbs = null;
	var gridPreview = false;
	var cloneSet = false;
	var threatsOpacity = 1.0
	var controlType;
	var copyThreat = false;
	var time_slider;
	var setHistory = true;
	var initOpts_nsslwrf14;
	var initOpts_nsslwrf15;
	var initOpts_nsslwrf17;
	var initOpts_ouMap;
	var initOpts_ouMap1km;
	var initOpts_ouMapProb;
	var initOpts_ouMapSpag;
	var initOpts_ukmet;
       	var initOpts_wof;
	var initOpts_hrrr;
	var initOpts_nam;
	var initOpts_gfs;
	var uhMember;
	var attrsLast;
	var showAT = true;
	var showT = true;
	var showS = true;
	var showL = false;
	var showB = true;
	var showW = false;
	var showPT = false;
	var activeStyle = true;
	var clon;
	var clat;
	var optsAvail;
	var optsName;
	var changeTimeNowLast;
	var lastWofDate;
	var timeDelta = 3600;
	var obsTimeLast;
	var obsDateLast;
	var nldnTimeLast;
	var nldnDateLast;
	var legacyDateLast;
       	var legacyTimeLast;
	var spcTimeLast;
	var spcDateLast;
	var azShearTimeLast;
	var azShearDateLast;
	var probSevereTimeLast;
       	var probSevereDateLast;
	var lightningTimeLast;
       	var lightningDateLast;
	var wofTimeLast;
        var wofDateLast;
	var radarObs = ['refl','refl1km','mesh','azshear'];
       	var hourMaxFields = ['uphlcy','hailcast','azshear','mesh'];
	var ncpMinutes = [0,5,10,15,20,25,30,35,40,45,50,55];
	var desk = 'NSSL';
	var lastRequestTime = 0;
	var validProbMin;
	var validProbMax;
	var validProbMinSevere = null;
       	var validProbMaxSevere = null;
	var validProbMinTornado = null;
       	var validProbMaxTornado = null;
	var validProbMinLightning = null;
	var validProbMaxLightning = null;
	var shearVal = null;
	var modifiedCentroid;
	var modifyFeatureAttrs;
	var configPanelLoaded = false;
	var modifyFeatureDrawn = false;
	var newScanHere = false;
	var autoProbType = 'severe';
	var nsslDateLast;
	var spcTornDateLast;
	var spcTorn1hrDateLast;
	var spcHailDateLast;
	var spcWindDateLast;
	var displayWoFImage1 = false;
	var displayWoFImage2 = false;
	var wofImage1;
	var wofImageLast1;
	var wofImage2;
        var wofImageLast2;
	var wofBounds;
	var modifiedObject = false;
	var timeStampModelLast;
	var boreStartX = -99;
	var boreStartY = 39;
	var boreEndX = -98;
	var boreEndY = 38;
	var getBore = false;
	var reqTime;
	var openBore = false;
	var boreURL;
	var objTitleLast = 'Direction';
	var objKeyLast = 'Direction';
	var objUnitsLast = 'deg.';
	var objType;
	var objTypeLast = 'probSevere';
	var objIDLast = -99;
	var objIDLast2 = -999;
	var reportsPanel;
	var newLSR = false;
	var allThreatObjects = [];
	var allProbVals = [];
	var gridAttrs;
	var gridState = false;
	var featList = [];
	var azShearFeatures = [];
	var probSevereFeatures = [];
	var lightningFeatures = [];
	var wofObjectsFeatures = [];
	var wofTracksFeatures = [];
	var pauseTime = 0;
	var resumeTime = 0;
	var uPointFeature = null;
	var swathEDD;
	var uPoint;
	var featEDD;
	var startTime2;
	var endTime2;
	var nsslPeriod = 'full';
	var wofLeadTime = 60;
	var wofLayer = 'points';
	var wofType = 'vor';
	var wofVal = 1;
	var wofVal2 = 1;
	var wofVal3 = 1;
	var wofValUnits = 'Member(s)';
	var wofValMin = 1;
	var wofValMax = 18;
	var wofValInc = 1;
	var wofIn = 3;
       	var wofIn2 = 3;
	var wofIn3 = 3;
	var wofInUnits = 's<sup>-1</sup>';
       	var wofInMin = 1;
       	var wofInMax = 15;
       	var wofInInc = 1;
	var chartFeature = null;
	var linkObjects = false;
	var linkObj1 = null;
        var linkTime1 = null;
	var linkThreat1 = null;
	var linkIssue1 = null;
	var linkAuto1 = null;
        var linkObj2 = null;
        var linkTime2 = null;
	var linkAttrs;
	var linkGeom;
	var linkTime;
	var analysis = false;
	var bufClone = null;
	var bufClone2 = null;
	var bufCloneTime = null;
	var bufMove = false;
	var objOffsetX = 0;
	var objOffsetY = 0;
	var autoSpd = -1;
	var autoDir = -1;
	var autoSpdSevere = -1;
        var autoDirSevere = -1;
	var autoSpdTornado = -1;
        var autoDirTornado = -1;
	var autoSpdLightning = -1;
        var autoDirLightning = -1;
	var objTypeMove = null;
	var mouseLon = null;
	var mouseLat = null;
	var activeIDs = [];
	var startPause = false;
	var resetting = false;
	var resetClone = null;
	var autoObjCheck = false;
	var showBlock = 1;
	var predFound = false;
